Readme.md
=> Fixed Swift syntax in Readme.

Bolts/Common/BFTask.m, BoltsTests/TaskTests.m
See https://github.com/BoltsFramework/Bolts-iOS/pull/67 for the original PR.
Updated with @nlutsenko-fb comments and squashed. Also added a small test.
=> Better -(NSString*)description for BFTask

.travis.yml
- Add podspec linting to Travis-CI
- Use `xctool` as it is fairly stable now
cc @grantland
=> Add podspec linting to Travis-CI.

Bolts/Common/BFTask.h, Bolts/Common/BFTask.m
=> Make BFTaskErrorDomain, BFTaskMultipleExceptionsException public.

LICENSE, PATENTS
https://code.facebook.com/posts/1639473982937255/updating-our-open-source-patent-grant/
=> Update Patent Grant and License

Bolts/Common/BFTask.m, BoltsTests/TaskTests.m
=> Fix State Priority Bug #87

Bolts.podspec, Bolts/Common/BoltsVersion.h, Bolts/Resources/Mac-Info.plist, Bolts/Resources/iOS-Info.plist, CHANGELOG.md
- Better subclassing support for BFTask, BFTaskCompletionSource, BFExecutor.
- Improved `taskForCompletionOfAllTasks:` to check for `error`/`exception` before cancelling a task.
- Fixed and improved layout of `BFAppLinkReturnToRefererController`.
- Improve optional importing for AppLinks code in umbrella header.
- Split Tasks and AppLinks in subspecs.
=> Release 1.1.5

.travis.yml
- Update Xcode to 6.4
- Parallelize iOS, OSX, Cocoapods tests
=> Update and parallelize Travis-CI.

README.md
=> Updated README to use new method signature.

Bolts.podspec, Bolts/Common/BoltsVersion.h, Bolts/Resources/Mac-Info.plist, Bolts/Resources/iOS-Info.plist, CHANGELOG.md
Update everything for Bolts 1.2.1
=> Bolts 1.2.1

Bolts/Common/BoltsVersion.h
Forgot to do this, I wish we had a script that did all of these for us...
=> Update the bolts version define to 1.2.2

Bolts.xcodeproj/xcshareddata/xcschemes/Bolts.xcscheme, Bolts.xcodeproj/xcshareddata/xcschemes/MacBolts.xcscheme
=> Update schemes for Xcode 7.

Bolts.podspec
Adding new stuff to our spec, also updated quotes and author.
Contributes to #155
=> Added watchOS2 support for Bolts pod.

Bolts.podspec, Bolts/Common/BoltsVersion.h, Bolts/Resources/Mac-Info.plist, Bolts/Resources/iOS-Info.plist, Bolts/Resources/tvOS-Info.plist, Bolts/Resources/watchOS-Info.plist, CHANGELOG.md
=> Bolts 1.3.0

.travis.yml, Bolts.xcodeproj/project.pbxproj, Bolts.xcodeproj/project.xcworkspace/xcshareddata/Bolts.xcscmblueprint, Bolts.xcodeproj/xcshareddata/xcschemes/Bolts-OSX.xcscheme, Bolts.xcodeproj/xcshareddata/xcschemes/Bolts-iOS.xcscheme, Bolts.xcodeproj/xcshareddata/xcschemes/Bolts-tvOS.xcscheme, scripts/build_framework.sh
Bolts-iOS
Bolts-OSX
Bolts-watchOS
Bolts-tvOS
=> Unify schemes and targets names.

scripts/build_release.sh
Deploy all the things!
Tested locally - works great.
=> Add tvOS SDK to deployment packages.

BoltsTests/TaskTests.m
No idea on how this wasn't caught by travis on the PR.
=> Fix TaskTests.testDescription

Bolts/Common/BFExecutor.m
This makes `-defaultExecutor` only run on a background thread if 10% or less of stack space is remaining.
This is significantly faster over a long chain of tasks, as we do not needlessly switch thread contexts, as well as being slightly faster than using `NSThread`'s thread-local dictionary.
The implementation is semi-portable, and should work on all Darwin-based systems, and will work on other platforms with minor tweaking of pointer math.
=> Changed `-defaultExecutor`'s dispatch policy to check stack space.

Bolts.podspec, Bolts/Common/BoltsVersion.h, Bolts/Resources/Mac-Info.plist, Bolts/Resources/iOS-Info.plist, Bolts/Resources/tvOS-Info.plist, Bolts/Resources/watchOS-Info.plist, CHANGELOG.md
=> Bolts 1.5.1 🔩

Bolts/Common/BFTask.m
=> Use Barrier version of OSAtomic in taskForCompletionOfAllTasks:.

.travis.yml, Bolts.xcodeproj/xcshareddata/xcschemes/Bolts-OSX.xcscheme, Bolts.xcodeproj/xcshareddata/xcschemes/Bolts-iOS-Dynamic.xcscheme, Bolts.xcodeproj/xcshareddata/xcschemes/Bolts-iOS.xcscheme, Bolts.xcodeproj/xcshareddata/xcschemes/Bolts-tvOS-Dynamic.xcscheme, Bolts.xcodeproj/xcshareddata/xcschemes/Bolts-tvOS.xcscheme, Bolts.xcodeproj/xcshareddata/xcschemes/Bolts-watchOS-Dynamic.xcscheme, Bolts.xcodeproj/xcshareddata/xcschemes/Bolts-watchOS.xcscheme
Also update schemes to the latest format.
=> Use Xcode 7.3 for Travis-CI.

BoltsTests/TaskTests.m
This test is flaky and failed in https://travis-ci.org/BoltsFramework/Bolts-ObjC/jobs/119398867
=> Fix flaky test in TaskTests.

.travis.yml, Bolts.xcodeproj/project.pbxproj, Bolts/Common/BFTask+Exceptions.h, Bolts/Common/BFTask+Exceptions.m, Bolts/Common/BFTask.h, Bolts/Common/BFTask.m, Bolts/Common/BFTaskCompletionSource.h, Bolts/Common/Bolts.h, BoltsTests/ExecutorTests.m, BoltsTests/TaskTests.m
Closes #250 .
First part of 2 step plan for #252 .
Thank you @hovox for inspiration and feature request!
=> Deprecate BFTask automatic exception catching.

Configurations/Bolts-iOS.xcconfig
Verified by building all schemes with destination set to device.
=> Update toolchain to unbreak compilation of dynamic frameworks.

Bolts.podspec, Bolts/Common/Bolts.m, Bolts/Resources/Info.plist, CHANGELOG.md
=> Bolts 1.8.1 🔩

.travis.yml
Should reduce the linting phase from 9 min to ~2 min.
=> Make Travis-CI run faster on CocoaPods phase.

Bolts/Common/BFTask.m, BoltsTests/TaskTests.m
Adds __unused declaration to make intention clear.
=> Sanitation fix

.gitmodules, .travis.yml, Bolts/iOS/BFWebViewAppLinkResolver.m, BoltsTests/AppLinkTests.m
=> Update shared configurations for Xcode 9.

scripts/build_framework.sh
To support Xcode 10
As per this comment: https://github.com/BoltsFramework/Bolts-ObjC/pull/323#discussion_r220561958
=> Perform clean by deleting build directory instead

Bolts.xcodeproj/project.pbxproj, Bolts.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Bolts.xcodeproj/xcshareddata/xcschemes/Bolts-iOS-Dynamic.xcscheme, Bolts.xcodeproj/xcshareddata/xcschemes/Bolts-iOS.xcscheme, Bolts.xcodeproj/xcshareddata/xcschemes/Bolts-macOS.xcscheme, Bolts.xcodeproj/xcshareddata/xcschemes/Bolts-tvOS-Dynamic.xcscheme, Bolts.xcodeproj/xcshareddata/xcschemes/Bolts-tvOS.xcscheme, Bolts.xcodeproj/xcshareddata/xcschemes/Bolts-watchOS-Dynamic.xcscheme, Bolts.xcodeproj/xcshareddata/xcschemes/Bolts-watchOS.xcscheme, CHANGELOG.md, Configurations/Version.xcconfig
- Created 1.9.1 in changelog. 
- Fixed some base internationalism depreciation warnings for 0 warnings.
=> Getting project ready for 1.9.1 release. 
