BoltsFramework/Bolts-ObjC

Bolts/Common/BFTask.h
Bolts/Common/BFTask.m
BoltsTests/TaskTests.m

Add taskForCompletionOfAllTaskResults to match Task.whenAllResult in Bolts-Android. All tasks should be of the same type.
Also add isFaulted property for consistency with Android and C#, tests for taskForCompletionOfAllTaskResults & missing tests for immediate completion of taskForCompletionOfAllTask and taskForCompletionOfAllTaskResults.
Similar to #74 but this adds a new method rather than modifying the existing one.

Add taskForCompletionOfAllTasksWithResults and faulted property

---

Bolts/iOS/BFAppLinkReturnToRefererView.m

Fixes #29. Increases size of hit targets by adding BFMarginY to the top and bottom of both the label and the close button height and also adding BFMarginX to the left and right of the close button width.

Increase Size of Hit Targets on BFAppLinkRefererView

---

Bolts.podspec
Bolts/Common/BoltsVersion.h
Bolts/Resources/Mac-Info.plist
Bolts/Resources/iOS-Info.plist
CHANGELOG.md

- New: Bolts for iOS is easily importable from Swift code (via `import Bolts`).
- New: Added `BFTask +taskForCompletionOfAllTaskResults`.
- New: Added `faulted` property on `BFTask`.
- New: Made `BFTaskErrorDomain` and `BFTaskMultipleExceptionsException` constants publicly available.
- New: `BFTask -description` now shows completed/cancelled/faulted status of a task.
cc @grantland

Release 1.1.4

---

Bolts/iOS/BFAppLinkReturnToRefererController.m
Bolts/iOS/BFAppLinkReturnToRefererView.h
Bolts/iOS/BFAppLinkReturnToRefererView.m

- if it is not explicitly closed with the 'X', it should show again if the app is re-opened from a referer
- rename _attachedToNavController ivar (per TODO)
- remove TODOs that are no longer relevant
- don't use autoresizing mask; the view has explicit layout already anyhow
- fix up CG struct usage to use the C functions
- allow intrinsic sizing of the referer view for use with auto-layout

Fix up the app link return to referer view/controller

---

Bolts.podspec
Bolts/Common/Bolts.h

This splits Bolts podspec into `Bolts/Tasks` and `Bolts/AppLinks`.
Fixes #60 and #80 (though in next release only).

Split AppLinks and Tasks into separate subspecs.

---

Bolts/Common/BFTask.m

When a continuation block is executed with a BFExecutor the internal block that makes the actual call check if the continuation block returns a BFTask, if that is the case a call to ```continueWithBlock:``` is made and the completion source is updated accordingly to the result of the task.
This pull request add code to check if the returned task is complete and update the completion source without made an extra call to ```continueWithBlock:```. This increase the performance on memory consumption and execution time. And also make sence :)

Avoid unnecessary call to ‘continueWithBlock:’ when a task is completed

---

Bolts/Common/BFTask.m

Avoid calling the getter directly. Instead use the property name ``completed`` as discussed in a [previous pull request]
[previous pull request]: https://github.com/BoltsFramework/Bolts-iOS/pull/57

Fix: use 'completed' accessor instead of 'isCompleted'

---

Bolts.xcodeproj/project.pbxproj
Bolts/Common/BFCancellationToken.h
Bolts/Common/BFCancellationToken.m
Bolts/Common/BFCancellationTokenRegistration.h
Bolts/Common/BFCancellationTokenRegistration.m
Bolts/Common/BFCancellationTokenSource.h
Bolts/Common/BFCancellationTokenSource.m
Bolts/Common/BFTask.h
Bolts/Common/BFTask.m
Bolts/Common/Bolts.h
BoltsTests/CancellationTests.m
BoltsTests/TaskTests.m

Initial CancellationToken & CancellationTokenSource implementation to match the C# API ([system.threading.cancellationtoken](https://msdn.microsoft.com/en-us/library/system.threading.cancellationtoken(v=vs.110).aspx) and [system.threading.cancellationtokensource](https://msdn.microsoft.com/en-us/library/system.threading.cancellationtokensource(v=vs.110).aspx)) and the cancellation API on Android (https://github.com/BoltsFramework/Bolts-Android/pull/53 and https://github.com/BoltsFramework/Bolts-Android/pull/56).

Add Task Cancellation

---

Bolts/Common/BFTask.m
BoltsTests/TaskTests.m

To be in sync with Bolts-Android:
https://github.com/BoltsFramework/Bolts-Android/blob/master/Bolts/src/bolts/Task.java#L832
Also written a test that was broken before.
cc @josephearl

Fixed never completed task if continuation returns a task and cancellation was requested.

---

Bolts.xcodeproj/project.pbxproj
Bolts.xcodeproj/xcshareddata/xcschemes/Bolts.xcscheme
Bolts.xcodeproj/xcshareddata/xcschemes/MacBolts.xcscheme
Bolts/Common/BFCancellationTokenSource.m
BoltsTests/AppLinkReturnToRefererViewTests.m
BoltsTests/BoltsTests.m
BoltsTests/CancellationTests.m
BoltsTests/ExecutorTests.m
BoltsTests/TaskTests.m

- Update project for Xcode 6.4
- Add tests for lines missing coverage.
- Remove dead code in BFCancellationTokenSource.

Add more tests, remove dead code to improve code coverage.

---

.travis.yml

This disables builds on all other branches except of master to reduce churn.
Pull Requests will still continue to build, tho.

Build only master for pushes on Travis-CI.

---

Bolts/iOS/BFAppLinkNavigation.m
BoltsTests/AppLinkTests.m

In the App Links reference implementation, remove the need to check canOpenURL and just use the openURL method directly.
Fixed unit tests, and tested using the App Links sample apps (AppLinkPasteboardSample).

Remove the need to check canOpenURL and just use openURL instead.

---

Bolts.xcodeproj/project.pbxproj
Bolts/iOS/BFAppLinkNavigation.m
Bolts/iOS/BFWebViewAppLinkResolver.m

These were deprecated in iOS 9 and are causing warnings to appear.
Use newly available methods if compiling for the latest platform and not having backwards compatibility.
cc @richardjrossiii
Fixes #126

Fixed deprecations in iOS 9 that cause warnings.

---

scripts/build_framework.sh
scripts/common.sh

Our scripts were failing when Bolts clone is in a path that has spaces - this fixes it.

Fix command line build scripts when bolts is contained in paths with spaces.

---

Bolts/iOS/BFAppLinkReturnToRefererView.m
BoltsTests/AppLinkReturnToRefererViewTests.m

When includeStatusBarInSize was set to BFIncludeStatusBarInSizeAlways, it didn't actually include the status bar in its size.

Fixed handling of BFIncludeStatusBarInSizeAlways

---

Bolts/iOS/BFURL.m
BoltsTests/AppLinkTests.m

Verify that the string is actually a string. This eliminates potential problems like if the URL is a number or anything else shady.
Fixes #114.

Fixed crash when creating a BFURL when target_url is null.

---

Bolts.xcodeproj/project.pbxproj
Bolts/Common/BFDefines.h
Bolts/Common/BFTask.h
Bolts/Common/BFTaskCompletionSource.h
Bolts/Common/Bolts.h

This support latest syntax in Xcode 7, and also is backward compatible via macro.
cc @grantland, @hallucinogen, @richardjrossiii

Add backward compatible Obj-C Generic support for Tasks.

---

Configurations/Bolts-iOS.xcconfig

Add the bitcode support if the binary is compiled with a iOS 9 SDK.
Please note that enabling this for iphonesimulator is not required and will break Xcode 6.4
cc @grantland @richardjrossiii

Add bitcode support to precompiled frameworks on iOS 9.

---

scripts/build_framework.sh

This fixes the problem that the framework is copied inside a framework folder, so we end up with
`Bolts.framework/Bolts.framework`.

Fixed packaging placing a framework inside a framework.

---

Configurations/Bolts-iOS.xcconfig

This properly builds and emits bitcode in code when built using Xcode 7 GM.
Tested the built framework against both Xcode 6.4 and 7.0 GM.
It also outputs `bitcode` slice into the binary, which could be observed by running `otool -l ...`

Update bitcode flag resolution for Xcode 7 GM.

---

Bolts.podspec
Bolts/Resources/Mac-Info.plist
Bolts/Resources/iOS-Info.plist
CHANGELOG.md

Depends on #144
Update everything for the release.
cc @grantland

Bolts 1.2.2

---

Bolts/Common/BFTask.m

Simple issue, you can't just cast a block type to another and expect it to work on every arch. For archs like PPC, this could have devastating stack-smashing side effects. Luckily, x86, ARM & friends are much nicer.

Fixed undefined behavior caused by casting block types.

---

.slather.yml
.travis.yml
README.md

Use code coverage from CodeCov.

---

Bolts.xcodeproj/project.pbxproj
Bolts.xcodeproj/xcshareddata/xcschemes/TVBolts.xcscheme
Bolts/Common/Bolts.h
Bolts/Resources/tvOS-Info.plist
Configurations/Bolts-tvOS.xcconfig
Configurations/BoltsTests-tvOS.xcconfig
Configurations/Shared/Platform/tvOS.xcconfig
scripts/build_framework.sh
scripts/common.sh

Added test target, framework target, and updated build scripts.
Only includes files included in MacBolts, (no app links, etc.)
Cannot add to travis until we have the latest Xcode beta available there.

Added tvOS build target

---

Bolts/iOS/BFAppLinkReturnToRefererView.m

These are implicitly converted from double to float - which produces warning.

Fix warnings when compiling for iOS 9.

---

Bolts.xcodeproj/project.pbxproj
Bolts.xcodeproj/xcshareddata/xcschemes/Bolts-watchOS.xcscheme
Bolts/Common/Bolts.h
Bolts/Resources/watchOS-Info.plist
Configurations/Bolts-watchOS.xcconfig
Configurations/Shared/Platform/watchOS.xcconfig

Added watchOS 2 target for Bolts. Same framework name and everything, but deployment and SDK is set to watchOS 2.
Please note - we are still distributing this as static framework, since we don't want to pollute the device with extra code.
Implements first part of #155

Added watchOS 2 target.

---

scripts/build_framework.sh

The build script tests that developer tools exist at certain paths by
using `test "$FOO"`--note the quotes around `$FOO`. When invoking those
tools, on the other hand, the paths to the tools are *not* wrapped in
quotes. This causes script failures when the paths include spaces.
Wrap the tool paths in quotes, to match how they are tested.

[scripts] Have `test` paths match execution paths

---

Bolts/Common/BFCancellationToken.m
Bolts/Common/BFCancellationTokenRegistration.m
Bolts/Common/BFExecutor.m
Bolts/Common/BFTask.m
Bolts/Common/BFTaskCompletionSource.m
Bolts/Common/Bolts.h
Bolts/iOS/BFAppLinkNavigation.m
Bolts/iOS/BFAppLink_Internal.h
Bolts/iOS/BFURL.m
Bolts/iOS/BFWebViewAppLinkResolver.m
BoltsTests/AppLinkReturnToRefererViewTests.m
BoltsTests/AppLinkTests.m
BoltsTests/BoltsTests.m
BoltsTests/CancellationTests.m
BoltsTests/ExecutorTests.m
BoltsTests/TaskTests.m

New warnings arouse due to usage of `xctoolchain` - fix them, as well as use modular imports in all tests.

Fix all new warnings, use modular imports in tests.

---

Bolts.podspec

Depends on #172, since it's not going to validate without Xcode 7.1.

Add tvOS to the list of supported platforms in podspec.

---

Configurations/Bolts-iOS.xcconfig

Enable bitcode for iOS 9.1 SDK.

---

Bolts/Common/BFTask.m
Bolts/Common/BFTaskCompletionSource.m

Move the code over, remove from private interface inside BFTaskCompletionSource.
As a result - we have 1 stack frame less in the stack trace when debugging.

Simplify settings properties on a Task from TaskCompletionSource.

---

Bolts/iOS/BFWebViewAppLinkResolver.m
BoltsTests/AppLinkTests.m

This interface idiom is the new one coming from TVOS.
The usage of ifdef here is essential, due to the fact that it might not be available.

Fix warning in BFWebViewAppLinkResolver.m.

---

Bolts/Common/BFTask.m

Accessing `_result` directly is not thread-safe, and it might have changed since the moment of invocation to the moment when the method returns.
This way we guarantee that `completed` and `result` are consistent, as well as accessing `result` here is fully thread-safe.

Fixed potential memory corruption on accessing a description of a task.

---

Bolts/Common/BFTask.m

The previous flow creates a task completion source and a task everytime, this flow has the following benefits:
- Creating 1 object less on construction of every task
- Properly follows `instancetype` return type, as it will always call into `self.init()`

Improve performance of task constructors.

---

Bolts/Common/BFTask.m

We don't need to create NSCondition or array of callbacks for tasks that are created already completed - so add more initializers for these, that allocate only `lock` and set the state.

Improve performance, memory usage for tasks that are created with result/error/exception/cancelled.

---

Bolts.xcodeproj/project.pbxproj
Bolts.xcodeproj/xcshareddata/xcschemes/Bolts-iOS.xcscheme

Doing this to make sure Xcode project file is not corrupted and works great.
Before - there was no ability to add a target dependency on `Bolts-iOS` via sub-project reference.
After recreating the target - it works great.

Recreate Bolts-iOS target to unbreak building via subproject reference.

---

Bolts/Common/BFCancellationToken.h
Bolts/Common/BFCancellationTokenRegistration.h
Bolts/Common/BFCancellationTokenSource.h
Bolts/Common/BFExecutor.h
Bolts/Common/BFTask.h
Bolts/Common/BFTaskCompletionSource.h
Bolts/Common/Bolts.h

Closes #161 
This pull request adds nullability annotations to Bolts Tasks.
Few highlights:
- This is somewhat potentially breaking, since there are no more implicitly unwrapped optionals in Swift after this is done
- This will work on any Xcode 6.3.1+ (which is going to be a requirement after this is merged in) (I can make it support versions before, but it will get way more polluted, and not sure on the actual impact)
- For qualifiers - this is still using `__nullable` instead of `_Nullable`, since the latter is available on Xcode 7.0+ only
Everything is split into separate commits for easier review, will squash later.
cc @grantland @hallucinogen

Added nullability annotations to Bolts Tasks.

---

Bolts/Common/BFTask.h
Bolts/Common/BFTask.m

At the moment of continuing from a BFTask that has a generic type - using `instancetype` will re-use the same generic type, whilst this is redundant and might not be the case.
By chaining the return type back to `BFTask *` we can make sure that we still return a BFTask, but it won't have a specific generic type anymore.

Improve BFTask.continue return type when used with generics.

---

Bolts.xcodeproj/project.pbxproj
Bolts.xcodeproj/xcshareddata/xcschemes/Bolts-iOS-Dynamic.xcscheme
Configurations/Bolts-iOS-Dynamic.xcconfig

Trying to address issue #152, this build I believe will support Carthage. The issue is that Bolts is currently a static library, whereas Carthage only supports dynamic libraries (hence why the Mac build works). I know there can be backwards compatibility issues so I've added a new target that builds dynamically. I'd really like this to get moved into production so that Facebook could support Carthage out of the box. Let me know if anything needs to be changed.

Dynamic Library for iOS Carthage Support

---

Bolts/Common/BFExecutor.m

This help for cleaning up after the garbage generated by a task, and will overall help memory pressure.
Note that we're *not* creating a pool for the immediate executor, as its purpose is to execute with as few side-effects as possible.

Make most executor types create an autorelease pool for each individual task.

---

Bolts.xcodeproj/xcshareddata/xcschemes/Bolts-iOS.xcscheme
Bolts/Common/BFCancellationToken.m
Bolts/Common/BFTask.m

These should be `nonatomic` anyway, since the public declaration lists them as such.
Fixes #215.

Fix Xcode 7.3 warnings.

---

Bolts/Common/BFTask.h
Bolts/Common/BFTask.m

At least say that this is an array of tasks and not something else.

Specify generic type for BFTask.taskForCompletionOfAllTasks*().

---

Bolts/Common/BFTask.h
Bolts/Common/BFTask.m

It's absolutely valid to have a `nil` result of a task - adjusting this method accordingly.

Remove nonnull requirement from BFTask.taskFromExecutor(_ ,block:).

---

Bolts/Common/BFCancellationToken.m
BoltsTests/CancellationTests.m

If you have registered at least 1 registration for the cancellation token and trying to dispose it - it will crash,
as we are enforcing that the disposal of registration happens before the disposal of cancellation token source,
even in case of internal API usage.
- Add a test that fails
- Fix the test by moving the disposal setter to after the registration disposal.

Fix disposing of CancellationTokenSource with registrations.

---

Bolts/Common/BFTask.h
Bolts/Common/BFTask.m
BoltsTests/TaskTests.m

Adds a race task, been using that code in a category in production apps for a while.
Heavily inspired by the `taskForCompletionOfAll:`

Adds race task

---

Bolts/iOS/BFAppLinkNavigation.m
scripts/build_framework.sh

No more BoltsVersion header, thus this line fails and returns non-zero code.

Unbreak build framework script.

---

Bolts/iOS/BFAppLinkNavigation.h
Bolts/iOS/BFAppLinkNavigation.m
BoltsTestUI/BoltsTestUI-Info.plist
BoltsTests/AppLinkTests.m

_Rehash of #26_
- Allows app to know the type of navigation that would result of calling `BFAppLinkNavigation`'s `+navigateToAppLink:error:` or `-navigate:` without having any side effects (i.e. no navigation)
- Also adds a test to ensure same output as `+navigateToAppLink:error:` without the side effects.
Relying on `-navigate:` completely hands off app behavior to Bolts. These no-side-effects functions allow apps to know what behavior Bolts is going to adopt with a given `BFAppLink`.
A developer might want to:
- completely hand off behavior if it's an AppLink with eligible targets or;
- use one of their own web views if it's just a regular link or a link that cannot be handled by any installed apps.

Add no-side-effects version of navigateToAppLink:error: and navigate:

---

Bolts/Common/BFTask.m
BoltsTests/TaskTests.m

Getter for `self.completed` is protected with a `@synchronized` call, so this should be thread-safe to call like that in a loop.
Superseds #135 and fixes #134.

Fix potential spurious thread wakeup.

---

Bolts/Common/BFTask.m

Surfaced via running tests on Parse framework many times and dead-locking, due to different lock order.

Fix potential deadlock in waitUntilFinished.

---

Bolts/Common/BFTask.h
Bolts/Common/BFTaskCompletionSource.h

This fixes some of the method name collisions when importing Bolts-ObjC into Swift 3.0.
Be aware - the naming is heavily inspired by Bolts-Swift to ease the transfer for any projects using Bolts-ObjC in Swift.
Fixes #276.

Fix method name collisions in Swift 3.0.

---

Bolts.xcodeproj/project.pbxproj
Bolts/Common/BFGeneric.h
Bolts/Common/BFTask.h
Bolts/Common/BFTask.m
Bolts/Common/Bolts.h

Instead of returning a `BFTask` with no generic type, or a generic type of 'NSNull' when there is no usable result from a task, we use the type 'BFVoid', which will always have a value of `nil`.
This allows you to provide a more enforced API contract to the caller, as sending any message to `BFVoid` will result in a compile time error.
Thank you @richardjrossiii for this hack, it simplifies a lot of boilerplate.
Also cc @gotemb as it would allow enforcing a lot of API contracts for you.

Add BFVoid macro to allow enforcing 'void' result types on BFTask.

---

Bolts/Common/BFCancellationToken.h
Bolts/Common/BFExecutor.h
Bolts/Common/BFExecutor.m
Bolts/Common/BFTask.h
Bolts/Common/BFTask.m

Declaring no arguments leads to block accepting any number of arguments
New warning introduced in Xcode 9

Blocks should have void as argument if it accepts no arguments

---

Bolts/Common/BFTask.m

Below analyze hints can be found:
```
BFTask.m:89:12: nil passed to a callee that requires a non-null 1st parameter.
...
return [[self alloc] initWithResult:result];
```
This PR fix the analyze warning. Please check if the diff makes any sense.

Fix Xcode analyze warning

---

Bolts.xcodeproj/project.pbxproj
Bolts/iOS/BFAppLinkReturnToRefererController.m

Xcode 9.2 introduced a new warning : `Implicit retain of 'self' within blocks`. 
Since then I have theses warning in my personal project. This pull request fix this.

Fix Implicit retain of self within blocks warnings

---

Bolts.podspec

There are 2 changes here:
1. Remove the per platform source_files and public_header_files globs
from the Tasks subspec because they are the same for all platforms
2. Remove the empty source_files definitions from the AppLinks subspec.
This subspec only supports iOS so these are unnecessary

Remove unnecessary podspec source_files
